### ISSUE TITLE
Fork for gojsonschema

### ISSUE THREAD

**Issue by Neo2308** [go-openapi/jsonpointer#21]
Hi folks, thanks for maintaining this repo!
Could we also start maintaining a fork for https://github.com/xeipuuv/gojsonschema?
(Please please)

**Comment by fredbi** [comment]
That repo is currently actively maintained and our toolkit doesn't depend on it.
Why should we maintain it?

**Comment by Neo2308** [comment]
1. Actually there haven't been any updates to the repo in the last 4 years, so it's fair to say that the repo is no longer maintained.
2. While your toolkit doesn't depend on it (a very fair point), the jsonpointer & jsonreference repos are direct alternatives to the corresponding repos from https://github.com/xeipuuv. The https://github.com/xeipuuv/gojsonschema repo is a heavily used repo without any major actively maintained forks. Here might be one of the best chances for a fork of it to get active maintenance.

(I understand that maintaining it could mean quite a bit of overhead, wanted to check if there is possibility for it to be maintained here anyway)

**Comment by fredbi** [comment]
No. Not interested. We have currently no use of this validator. There are other pure jsonschema validators out there and we maintain our own flavor for go-openapi (go-openapi/validate).

**Comment by Neo2308** [comment]
Thats fair. Thanks for the quick turnaround 😸!

**Comment by fredbi** [comment]
Thanks @Neo2308
